[target.'cfg(target_os = "linux")']
rustflags = ["-C","link-arg=-nostartfiles"]
[target.'cfg(target_os = "windows")']
rustflags = ["-C","link-args=/ENTRY:_main /SUBSYSTEM:console"]
[target.'cfg(target_os = "macos")']
rustflags = ["-C","link-args=-e __main -static -nostartfiles"]